package uk.wanat.theclinick.model;

public enum Speciality {
    ALLERGY, DENTISTRY, CARDIOLOGY, DERMATOLOGY, LARYNGOLOGY, ENDOCRINOLOGY, GYNAECOLOGY,
    NEUROLOGY, NURSE, DIETETICS, OPHTHALMOLOGY, ORTHOPAEDICS, PAEDIATRICS, PHYSIOTHERAPY, UROLOGY,
    GP, PSYCHIATRY, PSYCHOLOGY, ULTRASOUND

}
